//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcomApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Order_Product = new HashSet<Order_Product>();
        }
    
        public string Id { get; set; }
        public System.DateTime Date { get; set; }
        public double Total { get; set; }
        public int No_of_Item { get; set; }
        public string Customer { get; set; }
        public double Shipping { get; set; }
        public double Taxes { get; set; }
        public string Card_Number { get; set; }
        public string Address { get; set; }
        public string OrderNo { get; set; }
    
        public virtual Address Address1 { get; set; }
        public virtual Customer Customer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Product> Order_Product { get; set; }
    }
}
